name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build-windows:
    name: Build (Windows, ${{ matrix.build-config }}, MSVC)
    strategy:
      matrix:
        build-config: [Debug, Release]
      fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git ../vcpkg
          ../vcpkg/bootstrap-vcpkg

      - name: Build Project
        run: |
          mkdir build
          cmake "-DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake" -S . -B build
          cmake --build build --config ${{ matrix.build-config }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin-windows-${{ matrix.build-config }}
          path: |
            *
            !build/vcpkg_installed/**

  test-windows:
    name: Test
    needs:
      build-windows
    strategy:
      matrix:
        build-config: [Debug, Release]
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bin-windows-${{ matrix.build-config }}

      - name: Unit Tests
        run:
          build/test/${{ matrix.build-config }}/unit_tests

      - name: Integration Tests
        run:
          build/test/${{ matrix.build-config }}/integration_tests

  build-linux:
    name: Build (Linux, ${{ matrix.build-config }}, ${{ matrix.compiler }})
    strategy:
      matrix:
        build-config: [Debug, Release]
        compiler: [gcc, llvm]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true
          vcpkg: true

      - name: Build Project
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-config }} "-DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake" -S . -B build
          cmake --build build


      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin-linux-${{ matrix.build-config }}-${{ matrix.compiler }}
          path: |
            *
            !build/vcpkg_installed/**
